// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBluYwJbgXqUqKl8u0fadEsCqLPDci8l6o',
    appId: '1:759871142323:web:7578f76c9a16ad6ccaf3c6',
    messagingSenderId: '759871142323',
    projectId: 'flutter-jar',
    authDomain: 'flutter-jar.firebaseapp.com',
    storageBucket: 'flutter-jar.appspot.com',
    measurementId: 'G-G5RNRY44VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClEAAbHhl-mUzg-510wcqPjUWigxG66nA',
    appId: '1:759871142323:android:e858d14040629fcacaf3c6',
    messagingSenderId: '759871142323',
    projectId: 'flutter-jar',
    storageBucket: 'flutter-jar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm0B8l_EJLK3VLv0q4tIJqCThBBVbryzc',
    appId: '1:759871142323:ios:1e040b849ea18ccfcaf3c6',
    messagingSenderId: '759871142323',
    projectId: 'flutter-jar',
    storageBucket: 'flutter-jar.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm0B8l_EJLK3VLv0q4tIJqCThBBVbryzc',
    appId: '1:759871142323:ios:ad6bb463effc454dcaf3c6',
    messagingSenderId: '759871142323',
    projectId: 'flutter-jar',
    storageBucket: 'flutter-jar.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
